package br.com.reforcoonline.entity;

// Generated 04/01/2014 16:22:53 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Agenda generated by hbm2java
 */
@Entity
@Table(name = "agenda")
public class Agenda implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private Date dataHora;
	private String url;
	private Set<Pessoaagenda> pessoaagendas = new HashSet<Pessoaagenda>(0);

	public Agenda() {
	}

	public Agenda(Date dataHora, String url) {
		this.dataHora = dataHora;
		this.url = url;
	}

	public Agenda(Date dataHora, String url, Set<Pessoaagenda> pessoaagendas) {
		this.dataHora = dataHora;
		this.url = url;
		this.pessoaagendas = pessoaagendas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dataHora", nullable = false, length = 19)
	public Date getDataHora() {
		return this.dataHora;
	}

	public void setDataHora(Date dataHora) {
		this.dataHora = dataHora;
	}

	@Column(name = "url", nullable = false)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "agenda")
	public Set<Pessoaagenda> getPessoaagendas() {
		return this.pessoaagendas;
	}

	public void setPessoaagendas(Set<Pessoaagenda> pessoaagendas) {
		this.pessoaagendas = pessoaagendas;
	}

}
