package br.com.reforcoonline.entity;

// Generated 04/01/2014 16:22:53 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Area generated by hbm2java
 */
@Entity
@Table(name = "area")
public class Area implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String nome;
	private Set<Conhecimento> conhecimentos = new HashSet<Conhecimento>(0);

	public Area() {
	}

	public Area(String nome) {
		this.nome = nome;
	}

	public Area(String nome, Set<Conhecimento> conhecimentos) {
		this.nome = nome;
		this.conhecimentos = conhecimentos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nome", nullable = false, length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "area")
	public Set<Conhecimento> getConhecimentos() {
		return this.conhecimentos;
	}

	public void setConhecimentos(Set<Conhecimento> conhecimentos) {
		this.conhecimentos = conhecimentos;
	}

}
