package br.com.reforcoonline.entity;

// Generated 04/01/2014 16:22:53 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Transient;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name = "perfil", uniqueConstraints = @UniqueConstraint(columnNames = "nome"))
public class Perfil implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	public static final Integer PERFIL_PROFESSOR = 2;
	private Integer id;
	private String nome;
	private String indicadorAlcadaPerfil;
	private Set<Perfilusuario> perfilusuarios = new HashSet<Perfilusuario>(0);

	public enum AlcadaPerfil {
		ADMIN("00", "Admin"),
		PROFESSOR("01", "Professor");
		
		private String cod;
		private String nome;

		private AlcadaPerfil(String cod, String nome) {
			this.setCod(cod);
			this.setNome(nome);
		}

		public String getCod() {
			return cod;
		}

		public void setCod(String cod) {
			this.cod = cod;
		}

		public String getNome() {
			return nome;
		}

		public void setNome(String nome) {
			this.nome = nome;
		}
	}
	
	public Perfil() {
	}

	public Perfil(String nome, String indicadorAlcadaPerfil,
			Set<Perfilusuario> perfilusuarios) {
		this.nome = nome;
		this.indicadorAlcadaPerfil = indicadorAlcadaPerfil;
		this.perfilusuarios = perfilusuarios;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nome", unique = true, length = 100)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "indicadorAlcadaPerfil", length = 2)
	public String getIndicadorAlcadaPerfil() {
		return this.indicadorAlcadaPerfil;
	}

	public void setIndicadorAlcadaPerfil(String indicadorAlcadaPerfil) {
		this.indicadorAlcadaPerfil = indicadorAlcadaPerfil;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	public Set<Perfilusuario> getPerfilusuarios() {
		return this.perfilusuarios;
	}

	public void setPerfilusuarios(Set<Perfilusuario> perfilusuarios) {
		this.perfilusuarios = perfilusuarios;
	}
	
	@Transient
	public Boolean isAdmin() {
		if ( AlcadaPerfil.ADMIN.getCod().equals( this.indicadorAlcadaPerfil ) ) {
			return true;
		}
		
		return false;
	}

}
