package br.com.reforcoonline.entity;

// Generated 04/01/2014 16:22:53 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * Pessoa generated by hbm2java
 */
@Entity
@Table(name = "pessoa", uniqueConstraints = {
		@UniqueConstraint(columnNames = "idUsuario"),
		@UniqueConstraint(columnNames = "cpf"),
		@UniqueConstraint(columnNames = "email") })
public class Pessoa implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	
	private Usuario usuario;
	private String email;
	private String nome;
	private String cpf;
	private Set<Pessoaagenda> pessoaagendas = new HashSet<Pessoaagenda>(0);
	private Set<Conhecimentopessoa> conhecimentopessoas = new HashSet<Conhecimentopessoa>(
			0);

	public Pessoa() {
	}

	public Pessoa(String email, String nome, String cpf) {
		this.email = email;
		this.nome = nome;
		this.cpf = cpf;
	}

	public Pessoa(Usuario usuario, String email, String nome, String cpf,
			Set<Pessoaagenda> pessoaagendas,
			Set<Conhecimentopessoa> conhecimentopessoas) {
		this.usuario = usuario;
		this.email = email;
		this.nome = nome;
		this.cpf = cpf;
		this.pessoaagendas = pessoaagendas;
		this.conhecimentopessoas = conhecimentopessoas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUsuario", unique = true)
	@Cascade({CascadeType.ALL})
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "email", unique = true, nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "nome", nullable = false, length = 100)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "cpf", unique = true, nullable = false, length = 11)
	public String getCpf() {
		return this.cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pessoa")
	@Cascade({CascadeType.ALL})
	public Set<Pessoaagenda> getPessoaagendas() {
		return this.pessoaagendas;
	}

	public void setPessoaagendas(Set<Pessoaagenda> pessoaagendas) {
		this.pessoaagendas = pessoaagendas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pessoa")
	@Cascade({CascadeType.ALL})
	public Set<Conhecimentopessoa> getConhecimentopessoas() {
		return this.conhecimentopessoas;
	}

	public void setConhecimentopessoas(
			Set<Conhecimentopessoa> conhecimentopessoas) {
		this.conhecimentopessoas = conhecimentopessoas;
	}

}
